version: '3.7'
services:
  keycloak-authorization-server:
    image: jboss/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "7171:8081"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=8081"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=host.docker.internal"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=keycloak"
      - "DB_PASSWORD=keycloak"

#  keycloak:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin123
#      KEYCLOAK_LOGLEVEL: INFO
#      ROOT_LOGLEVEL: INFO
#    ports:
#      - "8080:8080"
#      - "8787:8787"
#    command:
#      - start-dev
#      - --features admin-fine-grained-authz