server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: service-registry-cluster

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
